# Workflow Configuration

documentation_generation:
  triggers:
    - push:
        branches: [main]
        paths: [src/**, docs/**]
    - pull_request:
        branches: [main]
  actions:
    - template_application
    - context_preservation
    - validation

validation_workflow:
  triggers:
    - push:
        paths: [docs/**]
    - schedule: daily
  checks:
    - completeness
    - format
    - links
    - context

error_tracking:
  triggers:
    - issues:
        types: [opened, edited]
        labels: [bug]
  actions:
    - pattern_analysis
    - solution_documentation
    - prevention_update

context_preservation:
  triggers:
    - push:
        paths: [docs/ai_context/**]
    - workflow_dispatch
  actions:
    - context_validation
    - history_update
    - integration_check