name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov sphinx sphinx-rtd-theme docstr-coverage bandit
    
    - name: Run tests
      run: pytest --cov=src tests/
    
    - name: Generate documentation
      run: |
        cd docs
        make html
    
    - name: Check docstring coverage
      run: docstr-coverage src --fail-under=80
    
    - name: Security check
      run: bandit -r src/