name: Documentation Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily check

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt

    - name: Link Validation
      run: |
        python docs/scripts/validate_links.py

    - name: Content Validation
      run: |
        python docs/scripts/validate_content.py

    - name: Coverage Check
      run: |
        python docs/scripts/check_coverage.py

    - name: Store Results
      if: always()
      run: |
        python docs/scripts/store_validation_results.py